### ISSUE TITLE
Great job getting the correct output for get_average_sentence_length! Now let's simplify a little bit

### ISSUE THREAD

**Issue by jmcrey** [Lilflow/pwp-capstones#1]
```
def get_average_sentence_length(text):
    text = text.replace("!", ".").replace("?", ".")
    text_split = text.split(".")
    text_split.pop()
    sentences_in_text = []
    for sentence in text_split:
        sentences_in_text.append(sentence.strip())
    sentence_words = []
    for sentence in sentences_in_text:
        sentence_words.append(sentence.split())
    sentence_lenghts = []
    for word in sentence_words:
        sentence_lenghts.append(len(word))
        
    avarage_sentence_lengths = sum(sentence_lenghts) / len(sentences_in_text)

    return avarage_sentence_lengths
```

Great job getting the correct output for this function! I just wanted to quickly show you a bit of a simpler way to get the same results. Basically, there is a way to combine all of the actions we took in the 3 separate `for` loops, and place all those actions into one bigger `for` loop. Here is an example way to combine all the `for` loops into one:

```
    sentence_lengths = []
    for sentence in text_split:
        if not sentence.strip():
            continue
        sentence_lengths.append(len(sentence.split()))
    avarage_sentence_lengths = sum(sentence_lengths) / len(sentence_lengths)
    return avarage_sentence_lengths
```

So, the first thing I did was change the `sentence.strip()` into an `if` statement. Basically, this `if` statement will remove any non-sentences from our list of sentences because `strip()` will return `None` on any sentence that does not have at least one character. So, all the empty / blank spaces will be skipped and our average will not count them. Thus, this `if` statement effectively accomplishes the same thing as our first `for` loop in the original implementation.

Second thing I did is I combine the two statements in the other two `for` loops. Notice that our second and third `for` loop effectively accomplish two things:

- 1) `sentence.split()` 
- 2) `len(sentence.split())`

Simply speaking, I took both of those actions and combined them into one larger statement. This combination allowed me to remove both `for` loops and place them into one larger `for` loop.

Again, this is just to make the implementation a bit simpler. The original implementation still works perfectly and can be kept that way. Combining the `for` loops simply makes the code more manageable because there is less of it. It also improves memory management because there are not as many lists. However, it does not greatly improve execution time as it is still O(n) in both implementations.

In essence, feel free to choose either implementation because both will work!

**Comment by Lilflow** [comment]
Thank you for this input. I will implement this in the future.
