### ISSUE TITLE
Make sure to only divide by appearances in frequency_comparison

### ISSUE THREAD

**Issue by jmcrey** [Lilflow/pwp-capstones#3]
```
def frequency_comparison(table1, table2):
    appearances = 0
    mutual_appearances = 0
    for key in table1.keys():
        if key in table2:
            if table1[key] >= table2[key]:
                appearances += table1[key]
                mutual_appearances += table2[key]
            else:
                appearances += table2[key]
                mutual_appearances += table1[key]
        else:
            appearances += table1[key]
    for key in table2:
        if key not in table1:
            appearances += table2[key]
    frequency_comparison_score = mutual_appearances / (appearances + mutual_appearances)
    return frequency_comparison_score
```

This is a really excellent implementation of this function. The one small change is that it our `frequency_comparison_score` should be `mutual_appearances / appearances` since `appearances` is the total number of appearances. So, we have to change our variable to be:

`frequency_comparison_score = mutual_appearances / appearances`

Other than that, this function is very well done. Great job!

P.S. Small tip: to avoid using the nomenclature of `table1[key]` and `table2[key]` in various places throughout our function, we can actually save these values to variables:

```
value1 = table1[key]
value2 = table2[key]
```

Then, we can use the variables throughout our function instead. This change will just save us from accessing our dictionary many times throughout the function, and it provides the reader with a solid understanding of what is being added where. But, either way will work just fine. This is just a tip!

**Comment by Lilflow** [comment]
I understand the mix up with the total number of appearances and thank you for the tip!
