### ISSUE TITLE
Small modification to our find_text_similarity function

### ISSUE THREAD

**Issue by jmcrey** [Lilflow/pwp-capstones#4]
```
def find_text_similarity(text1, text2):
    sentence_length_difference = percent_difference(get_average_sentence_length(text1), get_average_sentence_length(text2))
    sentence_length_similarity = abs(1 - sentence_length_difference)

    prepared_text1 = prepare_text(text1)
    prepared_text2 = prepare_text(text2)
    word_count_similarity = frequency_comparison(build_frequency_table(prepared_text1), build_frequency_table(prepared_text2))

    ngram_text1 = ngram_creator(prepare_text(text1))
    ngram_text2 = ngram_creator(prepare_text(text2))
    ngram_similarity = frequency_comparison(build_frequency_table(ngram_text1), build_frequency_table(ngram_text2))

    result = (sentence_length_similarity + word_count_similarity + ngram_similarity) / 3
    return result
```

Great job implementing this function! It returns the correct results for our similarity score. I just wanted to quickly point out that we can update this function to accept two `TextSample` objects, which help will simplify the implementation of this function (this is especially true once our program begins using the complete implementation of the `TextSample` object -- which is the very last box in the Jupyter notebook).

So, once we begin accepting the `TextSample` object to this function, we can being using class-level variables instead of implementing the entire calculation ourselves. Here is an example implementation where we use class-level variables instead of the raw text:

```
def find_text_similarity(sample1, sample2):
    sentence_length_difference = percent_difference(sample1.average_sentence_length, sample2.average_sentence_length)
    sentence_length_similarity = abs(1 - sentence_length_difference)
    word_count_similarity = frequency_comparison(sample1.word_count_frequency, sample2.word_count_frequency)
    ngram_similarity = frequency_comparison(sample1.ngram_frequency, sample2.ngram_frequency)
    return (sentence_length_similarity + word_count_similarity + ngram_similarity) / 3
```

Notice that when we accept `TextSample` objects as input, we can access the variables inside the class by using the `.`. For example, we can access the `average_sentence_length` (which is defined in our class as `self.average_sentence_length = get_average_sentence_length(self.raw_text)`) variable by typing:

`sample.average_sentence_length`

Also notice that using the class as our input saves us calculation time as many of the calculations are already done upon creating the class object (e.g. the average sentence length for the raw text). 

This is just a tip to show how using the classes can save us time and calculation. Either way, the original implementation works just fine!

**Comment by Lilflow** [comment]
Thank you for this in depth comment about using the class. Now I understand it.
