### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by jmcrey** [Lilflow/pwp-capstones#5]
### Criteria 1: Valid Python Code
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ The code included in the Jupyter notebook run without any errors.
 
### Criteria 2: Implementation of Project Requirements
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ Code produces the required suite of classes and functions and calls each function in an appropriate order. This is highlighted in the `find_text_similarity` function which calls each of the previously implemented functions in the appropriate order to achieve the correct result. Further, the `TextSample` class calls each function appropriately to initialize each variable. Another high point of this code base is that it is well-formatted and follows many of Python's best practices (e.g. it has descriptive variable names), which makes this code much easier to read and understand. Really nice job!
 
### Criteria 3: Software Architecture
* _Score Level:_ 3 (Meets Expectations)
* _Comment(s):_ The code is separated into distinct classes and functions, but there is 1 instance where the code repeats the functionality of another code sample. Specifically, in the `find_text_similarity` function, the code follows the same operations as the `TextSample` class because the `find_text_similarity` function accepts the raw text instead of the `TextSample` object (covered [here](https://github.com/Lilflow/pwp-capstones/issues/4)). Thus, the code was essentially copied and then modified instead of the code utilizing the predefined `TextSample` object's class-level variables. 
 
### Criteria 4: Uses Python Language Features
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ The code uses languages features appropriately -- if a task can be solved with a Python language feature, it is. A highlight for me is the use of `sum` and `len` in the `get_average_sentence_length` function.

### Criteria 5: Produces Accurate Output
* _Score Level:_ 2 (Approaches Expectations)
* _Comment(s):_ The code output is almost accurate; but, there was a slight calculation error in the `frequency_comparison` function that led to the output being slightly off (the error was covered [here](https://github.com/Lilflow/pwp-capstones/issues/3)).
 
### Overall Score: 17/20

Overall, this project was very well done. The code was well-organized, clear, accurate, and followed many of Python's best practices. Further, the code was well-formatted and made great use of Python's built-in functions. 

The main thing to focus on for the future is simplifying functions as much as we can. The simpler a function, the easier to understand, and the more manageable the code base becomes. 

One way to simplify a function is by trying to answer the question: "Is there a way to combine any of these operations?". For the first function, `get_average_sentence_length`, the answer was that we could combine all the operations of the separate `for` loops into one bigger `for` loop (covered [here](https://github.com/Lilflow/pwp-capstones/issues/1)). For the last function, the answer to this question was by accepting the `TextSample` object as input (covered [here](https://github.com/Lilflow/pwp-capstones/issues/4)). Just by trying to answer this one question, we can force ourselves to look for an alternate, more simple solution to our code. Of course, this skill will also come with time and experience, but thinking about combining functionality is one way to start building up this skill.

In any case, this project was still very well done! Excellent job!

**Comment by Lilflow** [comment]
Thank you so much for this in depth review. I appreciate all of your comments. This has been a good experience for me as a novice in coding.
